package com.innovfund.ai;

import com.innovfund.founder.entity.FounderProfile;
import com.innovfund.founder.repository.FounderProfileRepository;
import com.innovfund.startup.entity.Startup;
import com.innovfund.startup.entity.StartupStage;
import lombok.RequiredArgsConstructor;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.stereotype.Service;

import java.util.ArrayList;
import java.util.EnumMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.regex.Pattern;

/**
 * Deterministic heuristic evaluator (text-length + keyword-presence signals). This stands in for a
 * real LLM-backed evaluation until a Gemini API key is available (see {@link GeminiAiEvaluationService}).
 * It intentionally says so in its own output rather than pretending to be a trained model.
 */
@Service
@RequiredArgsConstructor
@ConditionalOnProperty(name = "app.ai.provider", havingValue = "mock", matchIfMissing = true)
public class MockAiEvaluationService implements AiEvaluationService {

    private static final String MODEL_VERSION = "mock-heuristic-v1";
    private static final Pattern NUMBER_PATTERN = Pattern.compile("\\d");
    private static final Pattern CURRENCY_PATTERN = Pattern.compile("(?i)(₹|\\$|rs\\.?|inr|usd|crore|lakh|million|billion)");

    private final FounderProfileRepository founderProfileRepository;

    @Override
    public AiEvaluationResult evaluate(Startup startup) {
        Map<RubricCategory, CategoryScore> scores = new EnumMap<>(RubricCategory.class);

        scores.put(RubricCategory.PROBLEM_CLARITY, scoreProblemClarity(startup));
        scores.put(RubricCategory.SOLUTION_QUALITY, scoreSolutionQuality(startup));
        scores.put(RubricCategory.MARKET_SIZE, scoreMarketSize(startup));
        scores.put(RubricCategory.BUSINESS_MODEL, scoreBusinessModel(startup));
        scores.put(RubricCategory.COMPETITOR_ANALYSIS, scoreCompetitorAnalysis(startup));
        scores.put(RubricCategory.TEAM_STRENGTH, scoreTeamStrength(startup));
        scores.put(RubricCategory.FINANCIAL_PLANNING, scoreFinancialPlanning(startup));
        scores.put(RubricCategory.SCALABILITY, scoreScalability(startup));
        scores.put(RubricCategory.FUNDING_JUSTIFICATION, scoreFundingJustification(startup));

        // weightedScore is on a 0-20*weight scale; normalize to a 0-100 overall score
        double overallOn100 = scores.values().stream()
                .mapToDouble(cs -> (cs.rawScore() / 20.0) * cs.category().getWeight() * 100.0)
                .sum();

        List<String> strengths = buildStrengths(scores);
        List<String> suggestions = buildSuggestions(scores);
        String readinessStatus = readinessStatus(overallOn100);
        String readinessConfidence = readinessConfidence(overallOn100);

        String summary = """
                This is an automated preliminary assessment based on structural heuristics \
                (text length, presence of key terms, and field completeness) applied to your \
                submitted startup information. It is NOT generated by a trained AI model yet \
                — a full LLM-based evaluation (Gemini) will replace this once configured. Use it \
                as a rough checklist of what a real investor evaluation would look for.""";

        return new AiEvaluationResult(scores, round(overallOn100), summary, strengths, suggestions,
                readinessStatus, readinessConfidence, MODEL_VERSION);
    }

    private List<String> buildStrengths(Map<RubricCategory, CategoryScore> scores) {
        List<String> strengths = new ArrayList<>();
        for (CategoryScore cs : scores.values()) {
            if (cs.rawScore() >= 16) {
                strengths.add(cs.category().getDisplayName() + ": " + cs.reasoning());
            }
        }
        if (strengths.isEmpty()) {
            strengths.add("No standout categories yet — every section has room to grow before this reads as a clear strength.");
        }
        return strengths;
    }

    private String readinessStatus(double overallOn100) {
        if (overallOn100 >= 80) return "Ready for Seed Investors";
        if (overallOn100 >= 60) return "Needs Improvement Before Pitching";
        return "Not Ready Yet";
    }

    private String readinessConfidence(double overallOn100) {
        if (overallOn100 >= 80) return "High";
        if (overallOn100 >= 60) return "Medium";
        return "Low";
    }

    private CategoryScore scoreProblemClarity(Startup s) {
        double score = lengthAndSpecificityScore(s.getProblem(), List.of("customers", "users", "struggle", "problem", "pain", "difficult", "need"));
        String reasoning = isBlank(s.getProblem())
                ? "No problem statement provided."
                : "Scored from the clarity/detail of the problem statement text.";
        return build(RubricCategory.PROBLEM_CLARITY, score, reasoning);
    }

    private CategoryScore scoreSolutionQuality(Startup s) {
        double score = lengthAndSpecificityScore(s.getSolution(), List.of("platform", "app", "software", "service", "solution", "technology", "ai", "automate"));
        String reasoning = isBlank(s.getSolution())
                ? "No solution description provided."
                : "Scored from the clarity/detail of the solution description.";
        return build(RubricCategory.SOLUTION_QUALITY, score, reasoning);
    }

    private CategoryScore scoreMarketSize(Startup s) {
        String text = nullToEmpty(s.getMarket());
        double score = 4;
        StringBuilder reasoning = new StringBuilder();
        if (isBlank(text)) {
            reasoning.append("No market information provided.");
        } else {
            score = lengthAndSpecificityScore(text, List.of("tam", "sam", "som", "market", "growing", "cagr"));
            if (CURRENCY_PATTERN.matcher(text).find()) {
                score = Math.min(20, score + 4);
                reasoning.append("Mentions concrete market size figures. ");
            } else {
                reasoning.append("No quantified market size (currency/CAGR figures) found — consider adding TAM/SAM/SOM numbers. ");
            }
        }
        return build(RubricCategory.MARKET_SIZE, score, reasoning.toString().trim());
    }

    private CategoryScore scoreBusinessModel(Startup s) {
        double score = lengthAndSpecificityScore(s.getBusinessModel(), List.of("subscription", "commission", "saas", "freemium", "revenue", "pricing", "fee", "b2b", "b2c", "marketplace"));
        String reasoning = isBlank(s.getBusinessModel())
                ? "No business model description provided."
                : "Scored from clarity of the revenue/monetization mechanics described.";
        return build(RubricCategory.BUSINESS_MODEL, score, reasoning);
    }

    private CategoryScore scoreCompetitorAnalysis(Startup s) {
        String text = nullToEmpty(s.getCompetitors());
        if (isBlank(text)) {
            return build(RubricCategory.COMPETITOR_ANALYSIS, 3, "No competitors listed — investors expect at least 2-3 named competitors with differentiation.");
        }
        long namedCount = java.util.Arrays.stream(text.split("[,;\\n]"))
                .map(String::trim)
                .filter(t -> !t.isEmpty())
                .count();
        double score;
        String reasoning;
        if (namedCount >= 2) {
            score = 15 + Math.min(5, namedCount);
            reasoning = "Lists " + namedCount + " competitors, which supports a credible competitive landscape.";
        } else {
            score = 9;
            reasoning = "Only one competitor mentioned — add more named competitors and explain differentiation.";
        }
        return build(RubricCategory.COMPETITOR_ANALYSIS, Math.min(20, score), reasoning);
    }

    private CategoryScore scoreTeamStrength(Startup s) {
        String bio = founderProfileRepository.findByUserId(s.getFounder().getId())
                .map(FounderProfile::getBio)
                .orElse(null);
        double score = lengthAndSpecificityScore(bio, List.of("experience", "founder", "years", "built", "led", "co-founder", "background"));
        String reasoning = isBlank(bio)
                ? "Founder profile bio is empty — a detailed founder bio (experience, past roles) improves investor confidence."
                : "Scored from the detail present in the founder's profile bio (a proxy for team strength in Phase 1).";
        return build(RubricCategory.TEAM_STRENGTH, score, reasoning);
    }

    private CategoryScore scoreFinancialPlanning(Startup s) {
        double score;
        String reasoning;
        if (s.getFundingGoal() == null || s.getFundingGoal().signum() <= 0) {
            score = 4;
            reasoning = "No funding goal set.";
        } else {
            score = 12;
            reasoning = "Funding goal is set. ";
            String revenueModel = nullToEmpty(s.getRevenueModel());
            if (!isBlank(revenueModel) && revenueModel.length() > 40) {
                score += 6;
                reasoning += "Revenue model is reasonably detailed, supporting the financial narrative.";
            } else {
                reasoning += "Consider detailing the revenue model further to justify financial projections.";
            }
        }
        return build(RubricCategory.FINANCIAL_PLANNING, Math.min(20, score), reasoning);
    }

    private CategoryScore scoreScalability(Startup s) {
        String text = nullToEmpty(s.getTargetAudience()) + " " + nullToEmpty(s.getMarket()) + " " + nullToEmpty(s.getSolution());
        double score = lengthAndSpecificityScore(text, List.of("scale", "national", "international", "platform", "network", "expand", "multiple cities", "global"));
        StartupStage stage = s.getStage();
        if (stage == StartupStage.GROWTH || stage == StartupStage.SCALING) {
            score = Math.min(20, score + 3);
        }
        String reasoning = "Scored from mentions of expansion/scale potential across target audience, market, and solution text, adjusted for startup stage.";
        return build(RubricCategory.SCALABILITY, score, reasoning);
    }

    private CategoryScore scoreFundingJustification(Startup s) {
        String text = nullToEmpty(s.getBusinessModel()) + " " + nullToEmpty(s.getSolution());
        double score = lengthAndSpecificityScore(text, List.of("hire", "hiring", "marketing", "expand", "r&d", "product development", "team", "acquisition"));
        String reasoning = (s.getFundingGoal() == null || s.getFundingGoal().signum() <= 0)
                ? "No funding goal to justify."
                : "Scored from whether the narrative explains what the raised funds will be used for (hiring, marketing, R&D, expansion).";
        return build(RubricCategory.FUNDING_JUSTIFICATION, score, reasoning);
    }

    private CategoryScore build(RubricCategory category, double rawScore, String reasoning) {
        double clamped = Math.max(0, Math.min(20, rawScore));
        double weighted = clamped * category.getWeight();
        return new CategoryScore(category, round(clamped), round(weighted), reasoning);
    }

    private double lengthAndSpecificityScore(String text, List<String> keywords) {
        if (isBlank(text)) {
            return 3;
        }
        int length = text.trim().length();
        double base;
        if (length < 30) {
            base = 6;
        } else if (length < 150) {
            base = 12;
        } else {
            base = 15;
        }
        String lower = text.toLowerCase(Locale.ROOT);
        long keywordHits = keywords.stream().filter(lower::contains).count();
        double bonus = Math.min(5, keywordHits * 1.5);
        return Math.min(20, base + bonus);
    }

    private List<String> buildSuggestions(Map<RubricCategory, CategoryScore> scores) {
        List<String> suggestions = new ArrayList<>();
        for (CategoryScore cs : scores.values()) {
            if (cs.rawScore() < 14) {
                suggestions.add(cs.category().getDisplayName() + ": " + cs.reasoning());
            }
        }
        if (suggestions.isEmpty()) {
            suggestions.add("Strong submission across all rubric categories — consider requesting a full LLM-based review once available for deeper qualitative feedback.");
        }
        return suggestions;
    }

    private boolean isBlank(String s) {
        return s == null || s.isBlank();
    }

    private String nullToEmpty(String s) {
        return s == null ? "" : s;
    }

    private double round(double value) {
        return Math.round(value * 100.0) / 100.0;
    }
}
