package com.innovfund.notification.entity;

public enum NotificationType {
    INVESTOR_FOLLOWED,
    NEW_COMMENT,
    NEW_POST_LIKE,
    FOUNDER_VERIFIED,
    INVESTOR_VERIFIED,
    STARTUP_VERIFIED,
    MEETING_REQUESTED,
    MEETING_ACCEPTED,
    MEETING_REJECTED,
    DUE_DILIGENCE_REQUESTED,
    DUE_DILIGENCE_APPROVED,
    NEW_MESSAGE,
    AI_RECOMMENDATION,
    INVESTOR_INTERESTED,
    INVESTMENT_RECEIVED,
    INTEREST_ACCEPTED,
    INTEREST_REJECTED
}
