import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { motion } from 'framer-motion';
import { ArrowRight, Brain, Calendar, ChevronDown, FileSearch, Heart, LineChart, MessageCircle, Rocket, Search, ShieldCheck, Sparkles, Trophy, Users, } from 'lucide-react';
import { Navbar } from '../components/layout/Navbar';
import { Button } from '../components/ui/Button';
import { Card } from '../components/ui/Card';
import { Badge } from '../components/ui/Badge';
import { StartupCard } from '../components/startup/StartupCard';
import { usePublishedStartups } from '../hooks/useStartups';
import { useFeaturedInvestors } from '../hooks/useInvestors';
import { useFeed } from '../hooks/useFeed';
import { useEvents } from '../hooks/useEvents';
const features = [
    {
        icon: Sparkles,
        title: 'AI Startup Evaluation',
        description: 'Get a transparent, rubric-based assessment of your startup across 9 weighted categories — with reasoning, not just a score.',
    },
    {
        icon: Users,
        title: 'Startup Feed',
        description: 'Share milestones, funding updates, and product launches. Investors follow, comment, and engage.',
    },
    {
        icon: LineChart,
        title: 'Funding Progress',
        description: 'Track your raise from goal to close, right alongside investor interest and engagement.',
    },
    {
        icon: FileSearch,
        title: 'Investor Discovery',
        description: 'Investors browse, filter, and follow startups by industry, stage, and funding range.',
    },
    {
        icon: ShieldCheck,
        title: 'Verified Community',
        description: 'Admins verify founders, investors, and startups — keeping the platform trustworthy.',
    },
    {
        icon: Brain,
        title: 'Built to Grow',
        description: 'From idea validation to due diligence and milestones — the full funding lifecycle in one place.',
    },
];
const steps = [
    { title: 'Create your startup profile', description: 'Problem, solution, business model, funding goal.' },
    { title: 'Get AI feedback', description: 'Run a structured evaluation and improve before you publish.' },
    { title: 'Publish & connect', description: 'Investors discover, follow, and express interest.' },
    { title: 'Raise & grow', description: 'Chat, meet, and track funding progress with milestone updates.' },
];
const categories = ['AI', 'FinTech', 'AgriTech', 'HealthTech', 'EdTech', 'E-commerce', 'SaaS', 'CleanTech'];
const testimonials = [
    {
        quote: "The AI evaluation caught gaps in our pitch we hadn't noticed — revenue model and competitor analysis were both thin. Fixed both before reaching out to a single investor.",
        role: 'Founder, using InnovateFund to validate and publish a startup',
    },
    {
        quote: 'Filtering by stage and funding range, then getting an AI match percentage with actual reasons attached, saved a lot of time compared to cold browsing.',
        role: 'Investor, using InnovateFund to discover startups',
    },
    {
        quote: 'Chat only opening after I accept interest keeps my inbox from filling with generic outreach — I only talk to investors I actually picked.',
        role: 'Founder, using InnovateFund to manage investor interest',
    },
];
const faqs = [
    {
        q: 'Is the AI evaluation a real trained model?',
        a: 'When a Gemini API key is configured, yes — startup evaluations, pitch rewrites, and the mentor chatbot are genuinely generated by Google Gemini. Without a key, the platform falls back to transparent rule-based heuristics that say so explicitly, rather than pretending to be AI.',
    },
    {
        q: 'Do investors see my full AI report?',
        a: "No. The detailed report — category scores, strengths, suggestions — is a private coaching tool for founders. Investors only see a small 'AI Verified Insights' summary: your overall readiness score and status.",
    },
    {
        q: 'How does investor matching work?',
        a: 'Matching uses TF-IDF and cosine similarity — a classic, explainable text-similarity technique — combined with industry and stage checks. It is deliberately not a black-box model, so every match percentage comes with concrete reasons.',
    },
    {
        q: 'When does chat open between a founder and an investor?',
        a: 'An investor expresses interest in a startup, and chat only opens once the founder accepts that interest — matching how real fundraising conversations start with founder consent.',
    },
];
export function LandingPage() {
    const navigate = useNavigate();
    const [searchInput, setSearchInput] = useState('');
    const [openFaq, setOpenFaq] = useState(null);
    const { data: featuredStartups, isLoading: loadingStartups } = usePublishedStartups({ page: 0, size: 6 });
    const { data: featuredInvestors, isLoading: loadingInvestors } = useFeaturedInvestors(6);
    const { data: feedPreview, isLoading: loadingFeed } = useFeed(0);
    const { data: events, isLoading: loadingEvents } = useEvents();
    const handleSearchSubmit = (e) => {
        e.preventDefault();
        navigate('/register');
    };
    return (<div className="min-h-screen">
      <Navbar />

      <section className="relative overflow-hidden px-4 pt-20 pb-16 sm:px-6">
        <div className="pointer-events-none absolute inset-x-0 -top-40 -z-10 h-[560px] opacity-30 blur-3xl" style={{
            background: 'radial-gradient(600px circle at 50% 0%, var(--color-brand-400), transparent 70%)',
        }}/>
        <div className="mx-auto max-w-3xl text-center">
          <motion.div initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5 }} className="mb-5 inline-flex items-center gap-2 rounded-full border border-slate-200 bg-white px-4 py-1.5 text-sm font-medium text-slate-600 shadow-sm dark:border-slate-800 dark:bg-slate-900 dark:text-slate-300">
            <Sparkles className="size-3.5 text-brand-500"/>
            AI-powered startup funding platform
          </motion.div>
          <motion.h1 initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5, delay: 0.05 }} className="text-4xl font-bold tracking-tight text-slate-900 sm:text-6xl dark:text-slate-100">
            From <span className="gradient-text">Idea</span> to{' '}
            <span className="gradient-text">Investment</span>
          </motion.h1>
          <motion.p initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5, delay: 0.1 }} className="mx-auto mt-5 max-w-xl text-lg text-slate-600 dark:text-slate-400">
            Validate your startup with AI, build an investor-ready profile, publish to a community
            of verified investors, and raise funding — all in one platform.
          </motion.p>

          <motion.form initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5, delay: 0.13 }} onSubmit={handleSearchSubmit} className="mx-auto mt-7 flex max-w-lg items-center gap-2">
            <div className="relative flex-1">
              <Search className="pointer-events-none absolute left-3.5 top-1/2 size-4.5 -translate-y-1/2 text-slate-400"/>
              <input value={searchInput} onChange={(e) => setSearchInput(e.target.value)} placeholder="Search startups by name, industry, or stage..." className="w-full rounded-full border border-slate-200 bg-white py-3 pl-10 pr-4 text-sm outline-none focus:border-brand-500 focus:ring-2 focus:ring-brand-500/20 dark:border-slate-700 dark:bg-slate-900"/>
            </div>
            <Button type="submit" size="lg">
              Search
            </Button>
          </motion.form>

          <motion.div initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5, delay: 0.15 }} className="mt-5 flex flex-wrap items-center justify-center gap-3">
            <Link to="/register">
              <Button size="lg">
                Get started free <ArrowRight className="size-4"/>
              </Button>
            </Link>
            <Link to="/login">
              <Button size="lg" variant="secondary">
                Log in
              </Button>
            </Link>
          </motion.div>
        </div>
      </section>

      <section className="px-4 pb-4 sm:px-6">
        <div className="mx-auto max-w-4xl">
          <div className="flex flex-wrap items-center justify-center gap-2">
            {categories.map((c) => (<Link key={c} to="/register">
                <Badge tone="slate" className="px-3 py-1.5 text-sm">
                  {c}
                </Badge>
              </Link>))}
          </div>
        </div>
      </section>

      {!loadingStartups && featuredStartups && featuredStartups.content.length > 0 && (<section className="px-4 py-16 sm:px-6">
          <div className="mx-auto max-w-6xl">
            <div className="mb-8 flex items-end justify-between">
              <div>
                <h2 className="text-2xl font-bold text-slate-900 sm:text-3xl dark:text-slate-100">Featured Startups</h2>
                <p className="mt-1 text-slate-500 dark:text-slate-400">Recently published, looking for investment.</p>
              </div>
              <Link to="/register" className="hidden text-sm font-medium text-brand-600 hover:underline sm:block dark:text-brand-400">
                View all <ArrowRight className="inline size-3.5"/>
              </Link>
            </div>
            <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
              {featuredStartups.content.slice(0, 6).map((s) => (<StartupCard key={s.id} startup={s} to="/register"/>))}
            </div>
          </div>
        </section>)}

      {!loadingInvestors && featuredInvestors && featuredInvestors.length > 0 && (<section className="bg-slate-50 px-4 py-16 sm:px-6 dark:bg-slate-900/40">
          <div className="mx-auto max-w-6xl">
            <div className="mb-8 text-center">
              <h2 className="text-2xl font-bold text-slate-900 sm:text-3xl dark:text-slate-100">Featured Investors</h2>
              <p className="mt-1 text-slate-500 dark:text-slate-400">Verified investors active on the platform.</p>
            </div>
            <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
              {featuredInvestors.map((inv) => (<Card key={inv.id} className="p-5">
                  <div className="flex items-center gap-3">
                    <div className="flex size-11 shrink-0 items-center justify-center rounded-xl bg-brand-50 text-brand-600 dark:bg-brand-500/10 dark:text-brand-300">
                      <Users className="size-5"/>
                    </div>
                    <div className="min-w-0">
                      <h3 className="truncate font-semibold text-slate-900 dark:text-slate-100">{inv.fullName}</h3>
                      {inv.firmName && <p className="truncate text-xs text-slate-500 dark:text-slate-400">{inv.firmName}</p>}
                    </div>
                    <ShieldCheck className="ml-auto size-5 shrink-0 text-brand-500" aria-label="Verified"/>
                  </div>
                  {inv.investmentInterests && (<p className="mt-3 line-clamp-2 text-sm text-slate-600 dark:text-slate-400">{inv.investmentInterests}</p>)}
                </Card>))}
            </div>
          </div>
        </section>)}

      <section className="px-4 py-16 sm:px-6">
        <div className="mx-auto max-w-6xl">
          <div className="mb-10 text-center">
            <h2 className="text-2xl font-bold text-slate-900 sm:text-3xl dark:text-slate-100">
              Everything the funding journey needs
            </h2>
            <p className="mt-2 text-slate-500 dark:text-slate-400">Not just a directory — an operating platform.</p>
          </div>
          <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
            {features.map((f, i) => (<motion.div key={f.title} initial={{ opacity: 0, y: 12 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: i * 0.05 }}>
                <Card className="h-full p-5">
                  <div className="mb-3 flex size-10 items-center justify-center rounded-xl bg-brand-50 text-brand-600 dark:bg-brand-500/10 dark:text-brand-300">
                    <f.icon className="size-5"/>
                  </div>
                  <h3 className="font-semibold text-slate-900 dark:text-slate-100">{f.title}</h3>
                  <p className="mt-1 text-sm text-slate-500 dark:text-slate-400">{f.description}</p>
                </Card>
              </motion.div>))}
          </div>
        </div>
      </section>

      <section className="bg-slate-50 px-4 py-16 sm:px-6 dark:bg-slate-900/40">
        <div className="mx-auto max-w-4xl">
          <div className="mb-10 text-center">
            <h2 className="text-2xl font-bold text-slate-900 sm:text-3xl dark:text-slate-100">How it works</h2>
          </div>
          <div className="grid gap-4 sm:grid-cols-4">
            {steps.map((s, i) => (<motion.div key={s.title} initial={{ opacity: 0, y: 12 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: i * 0.08 }} className="text-center">
                <div className="gradient-brand mx-auto mb-3 flex size-9 items-center justify-center rounded-full text-sm font-bold text-white">
                  {i + 1}
                </div>
                <h3 className="text-sm font-semibold text-slate-900 dark:text-slate-100">{s.title}</h3>
                <p className="mt-1 text-xs text-slate-500 dark:text-slate-400">{s.description}</p>
              </motion.div>))}
          </div>
        </div>
      </section>

      {!loadingFeed && feedPreview && feedPreview.content.length > 0 && (<section className="px-4 py-16 sm:px-6">
          <div className="mx-auto max-w-2xl">
            <div className="mb-8 text-center">
              <h2 className="text-2xl font-bold text-slate-900 sm:text-3xl dark:text-slate-100">From the Feed</h2>
              <p className="mt-1 text-slate-500 dark:text-slate-400">Real updates from founders and investors.</p>
            </div>
            <div className="space-y-3">
              {feedPreview.content.slice(0, 3).map((p) => (<Card key={p.id} className="p-4">
                  <div className="flex items-center gap-2">
                    <span className="font-medium text-slate-800 dark:text-slate-200">{p.authorName}</span>
                    {p.startupName && <span className="text-sm text-brand-600 dark:text-brand-400">@ {p.startupName}</span>}
                  </div>
                  <p className="mt-1.5 line-clamp-2 text-sm text-slate-600 dark:text-slate-400">{p.text}</p>
                  <div className="mt-2 flex items-center gap-4 text-xs text-slate-400">
                    <span className="flex items-center gap-1">
                      <Heart className="size-3.5"/>
                      {p.likeCount}
                    </span>
                    <span className="flex items-center gap-1">
                      <MessageCircle className="size-3.5"/>
                      {p.commentCount}
                    </span>
                  </div>
                </Card>))}
            </div>
            <div className="mt-6 text-center">
              <Link to="/register">
                <Button variant="secondary" size="sm">
                  Join to see the full feed
                </Button>
              </Link>
            </div>
          </div>
        </section>)}

      {!loadingEvents && events && events.length > 0 && (<section className="bg-slate-50 px-4 py-16 sm:px-6 dark:bg-slate-900/40">
          <div className="mx-auto max-w-4xl">
            <div className="mb-8 text-center">
              <h2 className="text-2xl font-bold text-slate-900 sm:text-3xl dark:text-slate-100">Events &amp; Competitions</h2>
            </div>
            <div className="grid gap-4 sm:grid-cols-3">
              {events.slice(0, 3).map((e) => (<Card key={e.id} className="p-4">
                  <Badge tone={e.type === 'COMPETITION' ? 'amber' : 'brand'}>
                    {e.type === 'COMPETITION' ? <Trophy className="size-3"/> : <Calendar className="size-3"/>}
                    {e.type === 'COMPETITION' ? 'Competition' : 'Event'}
                  </Badge>
                  <h3 className="mt-2 font-semibold text-slate-900 dark:text-slate-100">{e.title}</h3>
                  <p className="mt-1 text-xs text-slate-500 dark:text-slate-400">{new Date(e.eventDate).toLocaleDateString()}</p>
                </Card>))}
            </div>
          </div>
        </section>)}

      <section className="px-4 py-16 sm:px-6">
        <div className="mx-auto max-w-5xl">
          <div className="mb-10 text-center">
            <h2 className="text-2xl font-bold text-slate-900 sm:text-3xl dark:text-slate-100">What people are saying</h2>
          </div>
          <div className="grid gap-4 sm:grid-cols-3">
            {testimonials.map((t, i) => (<Card key={i} className="p-5">
                <p className="text-sm text-slate-700 dark:text-slate-300">&ldquo;{t.quote}&rdquo;</p>
                <p className="mt-3 text-xs text-slate-400">— {t.role}</p>
              </Card>))}
          </div>
        </div>
      </section>

      <section className="bg-slate-50 px-4 py-16 sm:px-6 dark:bg-slate-900/40">
        <div className="mx-auto max-w-2xl">
          <div className="mb-8 text-center">
            <h2 className="text-2xl font-bold text-slate-900 sm:text-3xl dark:text-slate-100">Frequently asked questions</h2>
          </div>
          <div className="space-y-2">
            {faqs.map((f, i) => (<Card key={i} className="overflow-hidden p-0">
                <button onClick={() => setOpenFaq(openFaq === i ? null : i)} className="flex w-full items-center justify-between px-5 py-4 text-left text-sm font-medium text-slate-800 dark:text-slate-200">
                  {f.q}
                  <ChevronDown className={`size-4 shrink-0 text-slate-400 transition-transform ${openFaq === i ? 'rotate-180' : ''}`}/>
                </button>
                {openFaq === i && <p className="px-5 pb-4 text-sm text-slate-600 dark:text-slate-400">{f.a}</p>}
              </Card>))}
          </div>
        </div>
      </section>

      <section className="px-4 py-20 sm:px-6">
        <Card className="gradient-brand mx-auto flex max-w-4xl flex-col items-center gap-4 p-10 text-center text-white">
          <Rocket className="size-8"/>
          <h2 className="text-2xl font-bold sm:text-3xl">Ready to build the future?</h2>
          <p className="max-w-md opacity-90">
            Join InnovateFund and take your startup from idea to investment.
          </p>
          <Link to="/register">
            <Button variant="secondary" size="lg">
              Create your free account
            </Button>
          </Link>
        </Card>
      </section>

      <footer className="border-t border-slate-200 px-4 py-8 text-center text-sm text-slate-500 sm:px-6 dark:border-slate-800 dark:text-slate-400">
        © {new Date().getFullYear()} InnovateFund. Built for founders and investors.
      </footer>
    </div>);
}
